services:
  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: computersDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d computersDB"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: computers_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/computersDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
